import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { subject, classLevel, country, topic, topicContent, additionalNotes } = await req.json();
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const isJSS = classLevel.startsWith("JSS");
    const levelDescription = isJSS 
      ? "junior secondary school (ages 10-14), use simple language, relatable examples, and focus on foundational concepts"
      : "senior secondary school (ages 15-18), use advanced terminology, critical analysis, and prepare students for external exams like WAEC/NECO";

    // Use topicContent if provided (from file upload), otherwise use topic
    const fullTopicContent = topicContent || topic;

    const systemPrompt = `You are an expert Nigerian/Ghanaian curriculum education specialist creating detailed lesson notes. 
You create comprehensive, engaging lesson plans tailored to ${country || "Nigerian"} education standards.
The target audience is ${levelDescription}.
Generate content that is culturally relevant, uses local examples, and follows the approved curriculum structure.
IMPORTANT: Base your lesson note EXACTLY on the topic/content provided by the user. Do not deviate from the given topic.`;

    const userPrompt = `Create a detailed lesson note for:

Subject: ${subject}
Class: ${classLevel}
Country: ${country || "Nigeria"}
Topic/Content to teach: ${fullTopicContent}

IMPORTANT: Generate the lesson note based EXACTLY on the topic/content provided above. The lesson should cover this specific topic thoroughly.

Use this EXACT format:

LESSON NOTE
============

Date: [Today's date]

Class: ${classLevel}

Subject: ${subject}

Topic: ${topic}

Sub-topic: [Generate an appropriate sub-topic based on the provided content]

Time: 40 minutes

Duration: 1 Period

Period/Day: First Period / Monday

Reference Book(s):
- [List 2-3 relevant approved textbooks for ${country || "Nigeria"}]
- ${country || "Nigeria"} National Curriculum

Instructional Material(s):
- [List 4-5 specific, relevant teaching aids for this topic]

Entry Behaviour:
[Describe what students should already know before this lesson - 2-3 sentences]

Behavioural Objectives:
By the end of this lesson, students should be able to:
1. [Specific, measurable objective using action verbs]
2. [Second objective]
3. [Third objective]
4. [Fourth objective]

Content:
[Provide comprehensive, detailed content covering:
- Clear definitions related to the topic
- Key concepts and principles from the provided topic
- Detailed explanations (at least 300 words)
- Examples relevant to ${country || "Nigerian"} context
- Important facts and figures]

Presentation in Steps:

Step I - Introduction (5 minutes):
[Detailed teacher activities and student engagement strategies]

Step II - Explanation/Development (15 minutes):
[Main teaching content with interactive elements]

Step III - Discussion/Activity (10 minutes):
[Group activities, demonstrations, or practical exercises]

Step IV - Application (5 minutes):
[How students apply what they learned]

Step V - Summary (5 minutes):
[Consolidation of key learning points]

Conclusion:
[2-3 sentences summarizing the lesson and linking to future topics]

Evaluation:
1. [Question aligned with objective 1]
2. [Question aligned with objective 2]
3. [Question aligned with objective 3]
4. [Question aligned with objective 4]

Assignment:
1. [Take-home task 1]
2. [Take-home task 2]
3. [Research or practical task]

${additionalNotes ? `Additional Requirements: ${additionalNotes}` : ""}

---
Generated by Teacher's Aid`;

    console.log("Calling Lovable AI Gateway for lesson generation...");
    console.log("Topic:", topic);
    console.log("Topic content length:", fullTopicContent?.length || 0);

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt }
        ],
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        console.error("Rate limit exceeded");
        return new Response(JSON.stringify({ error: "Rate limits exceeded, please try again later." }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (response.status === 402) {
        console.error("Payment required");
        return new Response(JSON.stringify({ error: "AI usage limit reached. Please add credits to continue." }), {
          status: 402,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      const errorText = await response.text();
      console.error("AI gateway error:", response.status, errorText);
      return new Response(JSON.stringify({ error: "AI gateway error" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const data = await response.json();
    const generatedContent = data.choices?.[0]?.message?.content;

    if (!generatedContent) {
      throw new Error("No content generated from AI");
    }

    console.log("Lesson generated successfully");

    return new Response(JSON.stringify({ content: generatedContent }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error in generate-lesson function:", error);
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    return new Response(JSON.stringify({ error: errorMessage }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
